--INSERT INTO user(login,coducm,dir,enabled, is_admin, is_player, isucm, name, password, phone, roles) VALUES ('admin@gmail.com', '0098-567898', 'C/La Milagrosa 12, 3B', 1, 1, 0, 1, 'Administrador', 'admin', '915468796', 'USER,ADMIN');
--INSERT INTO admin(dni, job, workplace, login) VALUES ('05950045D', 'Supervisor', 'normal', 'admin@gmail.com');
